// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstateMvc.Data;

namespace RealEstateMvc.Migrations
{
    [DbContext(typeof(RealEstateMvcContext))]
    [Migration("20210330142152_NewEntities")]
    partial class NewEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RealEstateMvc.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BaseSalary");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("DepartmentsId");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentsId");

                    b.ToTable("Consultant");
                });

            modelBuilder.Entity("RealEstateMvc.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("RealEstateMvc.Models.Rent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount");

                    b.Property<int?>("ConsultantId");

                    b.Property<int>("Contract");

                    b.Property<int>("ContractStatus");

                    b.Property<DateTime>("Date");

                    b.Property<int>("PropertyType");

                    b.HasKey("Id");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Rent");
                });

            modelBuilder.Entity("RealEstateMvc.Models.Consultant", b =>
                {
                    b.HasOne("RealEstateMvc.Models.Department", "Departments")
                        .WithMany("Consultants")
                        .HasForeignKey("DepartmentsId");
                });

            modelBuilder.Entity("RealEstateMvc.Models.Rent", b =>
                {
                    b.HasOne("RealEstateMvc.Models.Consultant", "Consultant")
                        .WithMany("Rents")
                        .HasForeignKey("ConsultantId");
                });
#pragma warning restore 612, 618
        }
    }
}
